{% set name = "nasdaq-data-link-mcp-os" %}
{% set version = "0.1.3.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
  run:
    - python >=3.10
    - mcp-cli >=1.6.0
    - nasdaq-data-link
    - pycountry

test:
  imports:
    - nasdaq_data_link_mcp_os

about:
  home: https://github.com/stefanoamorelli/nasdaq-data-link-mcp
  summary: Community maintained and open-source MCP server for the Nasdaq Data Link
  description: |
    Provides access to Nasdaq Data Link datasets through a Model Context Protocol (MCP) server.
    Maintained by Stefano Amorelli.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefano.amorelli
