name: Build and publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tool
        run: pip install --upgrade build setuptools

      - name: Install build tool
        run: pip install build

      - name: Clean previous builds
        run: rm -rf dist

      - name: Build package
        run: python -m build

      - name: Check package metadata
        run: pip install twine && twine check dist/*

      - name: Inspect build artifacts
        run: |
          unzip -l dist/*.whl

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.PYPI_TOKEN }}
