name: Build and publish to Conda

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: publish-to-conda
        uses: stefanoamorelli/conda-package-publish-action@v3-hotfix
        with:
          subDir: "conda"
          anacondaToken: ${{ secrets.ANACONDA_TOKEN }}
